image: gcc

# Build executable and delete it with make commands
build:
  stage: build

  script:
    - cd YahtzeeGame
    - make all
    - make clear

# run tests using make command
test:
  stage: test
  script:
    - cd YahtzeeGame
    - make tests_all
